name: ZenoraCoreUHC
version: 0.1.0
author: Mine
main: fr.mine.Main
load: startup

commands:
  corestat:
    description: Statut des joueurs dans la partie, avant le lancement

  coreetat:
    description: Change le statue de votre partie

  corehost:
    description: Lance la configuration de l'host

  coresethost:
    description: Donne les droit d'host a un jour
